services:
  # MariaDB database
  db:
    image: mariadb:10
    restart: unless-stopped
    networks:
      - appnet
    environment:
      # MARIADB_ROOT_PASSWORD is sensitive data and would normally be obfuscated
      # using Docker's secret management techniques. I left it visible here, however,
      # in the interest of convenience for the evaluator.
      MARIADB_ROOT_PASSWORD: password123
      # Creates a database called bc_store the first time this container is started
      MARIADB_DATABASE: bc_store
      # Creates a database user. All permissions are granted for the above database
      MARIADB_USER: bc_store
      MARIADB_PASSWORD: password456
    volumes:
      # Seeds the database
      - ./dbseed:/docker-entrypoint-initdb.d
      # Persists the data in the event container is stopped
      - ./dbfiles:/var/lib/mysql

  # Python API
  api:
    image: python-api
    restart: unless-stopped
    networks:
      - appnet
    depends_on:
      - db
    environment:
      DB_USER: bc_store
      DB_PASSWORD: password456
      DB_HOST: db
      # Default MariaDB port
      DB_PORT: 3306
      DATABASE_NAME: bc_store
    ports:
      # API will listen on port 8000
      - 8000:8000

  # React frontend
  frontend:
    image: react-frontend
    restart: unless-stopped
    networks:
      - appnet
    depends_on:
      - api
    ports:
      # Front-end application will be served at port 3000
      - 3000:3000

networks:
  appnet:
